#!/usr/bin/python3
"""Usage:
    pomodoreando [-dci] (pomodoro [--desc_largo] | <intervalo>...)

Opciones:
    -h --help         Muestra la ayuda
    -v --version      Versión
    -c --continuo     Hace que no tengas que confirmar para que comience el
                      siguiente intervalo
    -i --infinito     Hace que los intervalos sean infinitos
    --desc_largo      Hace que cada 4 pomodoros haya un descanso largo

Tutorial:
    Ponga como primer argumento el número de minutos que quiere que
    espere el cronómetro, o «pomodoro» para que haga intervalos de
    25 y 5 minutos.
    Cuando esté corriendo el cronómetro, puede pulsar la tecla «p»
    para parar o proseguir el cronómetro, y la letra «t» para terminar
    el cronómetro.
"""

import sys
import os
import threading
import time
from docopt import docopt

from __version__ import __version__

argumentos = docopt(__doc__, version=__version__)

terminar = False
parar = False


class Entrada(threading.Thread):
    def run(self):
        global terminar
        global parar

        self.entrada = input()
        if self.entrada == "t":
            terminar = True
        elif self.entrada == "p":
            parar = True
        else:
            self.run()



def cronometro(fin, nombre):
    global terminar
    global parar

    entrada = Entrada()

    segs = 0
    terminar = False
    parar = False

    entrada.start()
    print("El %s ha sido iniciado a %fmin." % (nombre.lower(), fin/60))

    while not terminar:
        print(time.ctime(segs)[14:19])
        time.sleep(1)
        segs += 1
        while parar:
            print("%s pausado." % nombre)
            entrada = input()
            if entrada == "p":
                parar = False
                entrada.start()
                print("%s proseguido." % nombre)
            elif entrada == "t":
                terminar = True
                parar = False
        if segs == fin:
            break
    else:
        print("El %s ha terminado." % nombre.lower())
        if terminar == True:
            return "t"


def main():
    if argumentos['pomodoro']:
        siguiente = "p"
        pomodoros = 0
        while siguiente != "t":
            if siguiente == "p":
                siguiente = cronometro(25*60, "Pomodoro")
                pomodoros += 1
                if not argumentos['--continuo']:
                    print("""
Si desea empezar el descanso corto de 5min, introduzca «d»,
y si desea empezar el descanso largo de 15min, introduzca «dl».
Si en cambio desea terminar, introduzca «t».""")
                    siguiente = input()
                else:
                    if siguiente == "t":
                        pass
                    elif pomodoros % 4 != 0:
                        siguiente = "d"
                    else:
                        siguiente = "dl"
            elif siguiente == "d":
                siguiente = cronometro(5*60, "Descanso")
                if not argumentos['--continuo']:
                    print("""
Si desea comenzar el siguiente pomodoro, introduzca «p».
Si en cambio desea terminar, introduzca «t».""")
                    siguiente = input()
                else:
                    if siguiente == "t":
                        pass
                    else:
                        siguiente = "p"
            elif siguiente == "dl":
                siguiente = cronometro(15*60, "Descanso")
                if not argumentos['--continuo']:
                    print("""
Si desea comenzar el siguiente pomodoro, introduzca «p».
Si en cambio desea terminar, introduzca «t».""")
                    siguiente = input()
                else:
                    if siguiente == "t":
                        pass
                    else:
                        siguiente = "p"
            else:
                print("""La letra que ha introducido no forma parte del intérprete.
Por favor, lea otra vez las instrucciones que le han sido proporcionadas.""")
                siguiente = input()

    else:
        argumentos['<intervalo>'] = [
            float(i) * 60 for i in argumentos['<intervalo>']
        ]
        siguiente = "i"
        while siguiente != "t":
            for i in argumentos['<intervalo>']:
                if siguiente == "i":
                    siguiente = cronometro(i, "Cronómetro")
                    if not argumentos['--continuo']:
                        print("""
Si desea seguir el intervalo, introduzca «i».
Si en cambio desea terminar, introduzca «t».""")
                        siguiente = input()
                        while siguiente != "i" and siguiente != "t":
                            print(
"""La letra que ha introducido no forma parte del intérprete.
Por favor, lea otra vez las instrucciones que le han sido proporcionadas.""")
                            siguiente = input()
                    else:
                        if siguiente != "t":
                            siguiente = "i"
                elif siguiente == "t":
                    break
            if not argumentos['--infinito']:
                siguiente = "t"

main()

os._exit(0)
